name: Tahoma2D Windows Build

on: [push, pull_request, workflow_dispatch]

jobs:
  Windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Create Package
        run: |
          ci-scripts\windows\tahoma-buildpkg.bat
          mkdir artifact
          cp -r toonz\build\Tahoma2D artifact
          Get-ChildItem -Path "artifact" -Recurse
      - uses: actions/upload-artifact@v4
        with:
          name: Tahoma2D-portable-win
          path: artifact
